### ISSUE TITLE
Inconsistency in SDK methods

### ISSUE THREAD

**Issue by omid** [fmeringdal/nettu-scheduler#31]
I just realized to delete a user, we need to pass `ID` but to delete a calendar we need to pass `DeleteCalendarInput` which contains one field for `ID`.

It's better to follow one pattern.

It can be there for all requests, delete/update/... and calendar/event/user/...

**Comment by fmeringdal** [comment]
Definitely. I think the pattern should be:
1. All methods will have just one argument ([This function](https://github.com/fmeringdal/nettu-scheduler/blob/master/scheduler/crates/sdk/src/calendar.rs#L188-L191) violates this for example).
2. If only one value is needed then use only simple argument with that value. For example: `fn foo(&self, user_id: ID)`
3. If several values are needed then define a new type and use that as input. For examaple 
```rust
struct CreateCalendarInput {
    pub user_id: ID,
    pub timezone: String,
    ...
}

fn create(
    &self,
    input: CreateCalendarInput,
)
```

**Comment by omid** [comment]
I 100% agree with what you said.
