### ISSUE TITLE
User Buckets

### ISSUE THREAD

**Issue by omid** [fmeringdal/nettu-scheduler#5]
Hello,

I'm new to this web app. :)

Is it possible to have user buckets/groups?
I mean, I want to have some groups of users and make it possible for "User A" to create an event for other users in their group.
Sure, "group" can be a "meta" tag we already have in the app, but "User A" should not be able to see other users in other groups, in ANY case, should not have access at all.

**Comment by fmeringdal** [comment]
Hi,

This type of authorization is currently not supported. But it is possible for your server to validate that a user is part of the required group and if so forward the request to the `nettu-scheduler` server, this was only users that are part of the group should have access to the resources beloning to that group.

Let me know if that answers your question :)

**Comment by omid** [comment]
Thanks. Yes, it does 👍🏼
